#!/bin/bash

set -e

if [ -a /var/www/$APP_NAME/current/.ruby-version ]
then
	echo ".ruby-version file found"
	VERSION=$(cat /var/www/$APP_NAME/current/.ruby-version)
	echo "installing ruby $VERSION"
	su root -c 'source /usr/local/rvm/scripts/rvm && rvm install $VERSION --default'
	echo "now what?"
else
	echo "no .ruby-version file found"
fi

source /usr/local/rvm/scripts/rvm
cd /var/www/$APP_NAME/current

bundle install

if ! gem spec passenger > /dev/null 2>&1; then 
  gem install passenger
fi

bundle exec rake db:create
bundle exec rake db:migrate

foreman start -p 80 -e $RAILS_ENV
